# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MechPal' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MechPal
  source 'https://github.com/CocoaPods/Specs.git'
  
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  target 'MechPalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MechPalUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
      
     
end
